server:
  port: 9090

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-register-service
              uri: lb://AUTH-REGISTER-SERVICE
              predicates:
                - Path=/api/auth/**
            - id: incident-service
              uri: lb://INCIDENT-SERVICE
              predicates:
                - Path=/api/incidents/**
            - id: ai-analysis-server
              uri: http://ai-analysis-server:5000
              predicates:
                - Path=/api/v1/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9091/realms/devflow}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/devflow/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://discovery-server:8761/eureka/}
  instance:
    prefer-ip-address: true